# Generated by Django 2.2 on 2020-01-23 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrel_code', models.CharField(max_length=5)),
                ('carrel_type', models.CharField(choices=[('S', 'Single Occupancy'), ('D', 'Double Occupancy')], default=None, max_length=1)),
                ('vacant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('floor', models.CharField(choices=[('Q', 'Quiet Study'), ('S', 'Silent Study')], default=None, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('student_ID', models.CharField(max_length=8, null=True, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], default=None, max_length=1, null=True)),
                ('carrel_allotted', models.BooleanField(default=False)),
                ('Carrel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selection.Carrel')),
                ('Program', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='selection.Program')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selection.Floor')),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='carrel',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection.Floor'),
        ),
    ]
